/********************************************************************************************************************/
/*																													*/
/*	Project:	InDesign Plug-in																					*/
/*																													*/
/*	Module:		precompiled.h																						*/
/*																													*/
/*	Created:	27.04.12 bu																							*/
/*																													*/
/*	Modified:																										*/
/*																													*/
/********************************************************************************************************************/

#include "VCPlugInHeaders.h"

#include <algorithm>
#include <deque>
#include <boost/algorithm/string/replace.hpp>
#include <boost/format.hpp>
#include <CAlert.h>
#include <CActionComponent.h>
#include <CDragDropTargetFlavorHelper.h>
#include <CIdleTask.h>
#include <CmdUtils.h>
#include <CObserver.h>
#include <CPMUnknown.h>
#include <DataObjectIterator.h>
#include <EPSID.h>
#include <ErrorUtils.h>
#include <FileUtils.h>
#include <IActionFilter.h>
#include <IActionStateList.h>
#include <IActiveContext.h>
#include <IActionManager.h>
#include <IApplication.h>
#include <IBaselineFrameGridData.h>
#include <IBoolData.h>
#include <IClassIDData.h>
#include <IColumns.h> // CC
#include <ICommand.h>
#include <IControlView.h>
#include <ICoreFilename.h>	
#include <ICoreFilenameUtils.h>
#include <ICreateMCFrameData.h>
#include <IDataExchangeHandler.h>
#include <IDataLinkReference.h>
#include <IDFile.h>
#include <IDocFileHandler.h>
#include <IDocument.h>
#include <IDocumentLayer.h>
#include <IDocumentList.h>
#include <IDocumentUIUtils.h>
#include <IDocSetupCmdData.h>
#include <IDocumentCommands.h>
#include <IDocumentUIUtils.h>
#include <IDocumentUtils.h>
#include <IDragDropTarget.h>
#include <IEPSExportPreferences.h> 
#include <IEPSExportPrefsCmdData.h>
#include <IExportEPSCmdData.h>
#include <IFrameType.h>
#include <IGeometry.h>
#include <IGeometryFacade.h>
#include <IGlobalRecompose.h>
#include <IGraphicFrameData.h>
#include <IHierarchy.h>
#include <IImageAttributes.h>
#include <IImportCore.h>
#include <IImportManager.h>
#include <IImportManagerOptions.h>
#include <IIntData.h>
#include <IItemStrand.h>
#include <IK2ServiceProvider.h>
#include <IK2ServiceRegistry.h>
#include <ILayerList.h>
#include <ILayerUtils.h>
#include <ILayoutCmdData.h>
#include <ILayoutControlData.h>
#include <ILayoutSelectionSuite.h>
#include <ILayoutUIUtils.h>
#include <ImageID.h>
#include <IMargins.h>
#include <IMultiColumnItemData.h>
#include <IMultiColumnTextFrame.h>
#include <INewDocCmdData.h>
#include <INewPageItemCmdData.h>
#include <INewSpreadCmdData.h>
#include <IObserver.h>
#include <IOpenFileCmdData.h>
#include <IOpenFileDialog.h>
#include <IOpenManager.h>
#include <IPageColumnsCmdData.h>
#include <IPageItemLayerData.h>
#include <IPageItemScrapUtils.h>
#include <IPageList.h>
#include <IPageMarginsCmdData.h>
#include <IPasteboardUtils.h>
#include <IPathUtils.h>
#include <IPDFExportPrefs.h>
#include <IPDFExptStyleListMgr.h>
#include <IPDFSecurityPrefs.h>
#include <IPlacePIData.h>
#include <IPlugInList.h>
#include <IPMStream.h>
#include <IPrintCmdData.h>
#include <IPrintData.h>
#include <IPrintDeviceInfo.h>
#include <IPrStStyleListMgr.h>
#include <IRenderingObject.h>
#include <ISaveFileDialog.h>
#include <ISAXAttributes.h>
#include <ISAXServices.h>
#include <ISAXContentHandler.h>
#include <ISAXParserOptions.h>
#include <IScriptManager.h>
#include <IScriptEngine.h>
#include <IScriptRunner.h>
#include <IScriptUtils.h>
#include <ISelectionManager.h>
#include <ISelectionUtils.h>
#include <ISession.h>
#include <ISpread.h>
#include <ISpreadLayer.h>
#include <ISpreadList.h>
#include <IStartupShutdownService.h>
#include <IStoryList.h>
#include <ISubject.h>
#include <ISuppressedUI.h>
#include <ISwatchList.h>
#include <ISwatchUtils.h>
#include <ISysFileData.h>
#include <ISysFileListData.h>
#include <ITextColumnSizer.h>
#include <ITextFrameColumn.h>
#include <ITextModel.h>
#include <ITextModelCmds.h>
#include <ITextVariable.h>
#include <ITextVariableChangeData.h>
#include <ITextVariableFacade.h>
#include <ITextVariableSuite.h>
#include <ITextVariableTable.h>
#include <ITOPFrameData.h>
#include <IUIDData.h>
#include <IUIFlagData.h>
#include <IWaxIterator.h>
#include <IWaxStrand.h>
#include <IWindow.h>
#include <IWorkspace.h>
#include <JavaScriptID.h>
#include <JPEGFilterID.h>
#include <LayerID.h>
#include <list>
#include <map>
#include <NameInfo.h>
#include <PageSetupDialogID.h>
#include <PDFID.h>
#include <PersistUtils.h>
#include <PlatformChar.h>
#include <PlugIn.h>
#include <PMFlavorTypes.h> 
#include <PMLocaleId.h>
#include <PMPathPoint.h>
#include <PreferenceUtils.h>
#include <SDKFileHelper.h>
#include <SDKLayoutHelper.h>
#include <SnapshotUtils.h>
#include <SplineID.h>
#include <StreamUtil.h>
#include <SuppressedUIXMLDefs.h>
#include <TextIterator.h>
#include <ITransform.h>
#include <TransformUtils.h>
#include <ITriStateData.h>
#include <UIDList.h>
#include <Utils.h>

#if WINOS
#include <WLocaleSetting.h>  
#endif

#include "AdDocPI.h"
#include "CMyStream.h"
#include "DocMgr.h"
#include "DocWchID.h"
#include "DocResources.h"
#include "ErrorCheckingLogging.h"
#include "Functions.h"
#include "IDFactory_cpp.h"
#include "idtypes.h" 
#include "FrameUtils.h"
#include "ImageLinkUtils.h"
#include "IndComm.h"
#include "InterfaceFactory.h"
#include "JavascriptHelper.h"
#include "OpenPlaceID.h"
#include "PathAux.h"
#include "PluginConfiguration.h"
#include "PluginConfigurationImpl.h"
#include "PluginLogger.h"
#include "SuppUISuppressedUI.h"
#include "ShuksanID.h"
#include "UnifiedAux.h"
#include "ISelSuite.h"
#include "XMLConfigSAXContentHandler.h"
#include "XMLConfigurationReader.h"
#include "IOpenLayoutCmdData.h"
#include <IImportResourceCmdData.h>
#include "ITextFrameFacade.h"
#include "IURIUtils.h"
#include <ILinkManager.h>

#ifdef CC
#define GrabCString	GetUTF8String
#endif
